Qtuan1401/add/SignupPage
fc5y/user-fe pull request #17
Opened 2020-10-01 16:28 UTC by qtuan1401

Add signup page, add new image and add new route into App.js

2020-10-01 17:17 UTC, kc97ble commented
this branch should not contain commits from enter page.

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/LoginPage/failed.js
> +import CloseButton from '../../../assets/images/XMLID 1429.png';
please rename the file

e.g. "close-button.png"

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/LoginPage/index.js
> +    }
Don't use global variable.

React does not watch global variables. Even if `isRedirect` is changed, there is no guarantee that `render` function will be triggered.

Use React's state for this purpose.

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/LoginPage/login.scss
> +  .popup {
rename to `overlay` or `popupOverlay` or `overlayBackground`

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/LoginPage/login.scss
> +    height: 1080px;
what if user's screen resolution is not 1920 x 1080?

to make the element full screen, use:
```
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
```

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/LoginPage/login.scss
> +    box-shadow: 0px 0px 12px rgba(188, 188, 188, 0.25);
Avoid `position: absolute` for simple components.

There are no good reasons to use `position: absolute` here.

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/SignupPage/index.js
> +let chkAgreed = true;
Don't use global variables.

(global consts are okay)

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/SignupPage/index.js
> +                </div>
Abstract these input fields into components.

You are having a lot of duplications here.

2020-10-01 17:36 UTC, kc97ble commented on src/app/components/SignupPage/index.js
> +                </div>
e.g.

```
function InputText({ label, name, onChange, value }) {
...
}
```

2020-10-02 01:33 UTC, hnngo requested changes

2020-10-02 01:33 UTC, hnngo commented on src/app/components/LoginPage/index.js
> +      [name]: value,
is it wrong, so name and value here are Array?

2020-10-02 01:33 UTC, hnngo commented on src/app/components/SignupPage/failed.scss
> +    button {
Avoid general element tag

2020-10-02 05:12 UTC, hnngo requested changes

2020-10-02 05:12 UTC, hnngo commented on src/app/components/EnterPage/enter.scss
> +@import url('https://fonts.googleapis.com/css?family=Mulish');
Remove this line, font has been added once in html file

2020-10-02 15:31 UTC, closed without merging