Fix UI and errors responding bugs
fc5y/user-fe pull request #79
Opened 2020-12-05 13:59 UTC by qtuan1401

2020-12-05 14:16 UTC, qtuan1401 commented
Demo: https://drive.google.com/file/d/1CrEVcaldmpz1Xr3G6QQnwpmSp58x308D/view?usp=sharing

2020-12-05 14:17 UTC, qtuan1401 commented
Demo: https://drive.google.com/file/d/1CrEVcaldmpz1Xr3G6QQnwpmSp58x308D/view?usp=sharing

2020-12-08 14:05 UTC, hnngo requested changes

2020-12-08 14:05 UTC, hnngo commented on src/app/containers/LoginPage/index.js
> +    <div className={styles.container}>
Why don't we change the style of `MainPanel`

2020-12-08 15:43 UTC, hnngo approved these changes

2020-12-08 15:44 UTC, merged